#######GENERAL#############
server:
  port: 8085
camel:
  springboot:
    name: apache-camel-demo
    main-run-controller: true
quartz:
  retrieve:
    demo-once: "timer://runOnce?repeatCount=1&delay=5000"
    demo-cron: "quartz://baseProjectGroup/baseProjectJob?cron=0+0/1+*+*+*+?+*"
finish-process:
  create-file: "file://C:/test/?fileName=terminated"

##########  API ###############

api:
  url:
    predict-gender: "https://api.genderize.io?name=::NAME::"
    random-name: "https://namey.muffinlabs.com/name.json?count=10&with_surname=false&frequency=common"
    predict-age: "https://api.agify.io?name=::NAME::"
